import 'dart:ui';

import 'package:google_maps_flutter/google_maps_flutter.dart';


Color darkblue=Color(0xff0D1B2B);
Color blue=Color(0xff2B46D6);
int currentIndex = 0;
Color lightblue=const Color(0xfff8fafc);
Color bgcolor=Color(0xff0d0d0d);
bool darktheme=false;

 LatLng ?  currentLocation;
List<Map<String, dynamic>> groupedCarModels = [
{
"Manufacturer": "Hyundai",
"Models": [
"Accent HCL",
"Accent RB",
"Atos",
"Avante",
"Bayon",
"Creta",
"Creta SU2",
"Elantra AD",
"Elantra CN7",
"Elantra HD",
"Elantra MD",
"Elantra",
"Elantra Coupe",
"Excel",
"Fx",
"Galloper",
"Getz",
"Grand i10",
"H1",
"H100",
"I10",
"I20",
"I30",
"IX 35",
"Ix20",
"Kona",
"Matrix",
"Santa fe",
"Santamo",
"Solaris",
"Sonata",
"Terracan",
"Tiburon",
"Trajet",
"Tucson GDI",
"Tucson Turbo GDI",
"Tucson",
"Veloster",
"Verna",
"Viva",
"XD",
],
},
{
"Manufacturer": "Kia",
"Models": [
"Cadenza",
"Carens",
"Carnival",
"Ceed",
"Grand Crerato",
"Cerato",
"Cerato Koup",
"Clarus",
"EV6",
"Forte",
"K3",
"K5",
"Niro",
"Optima",
"Pegas",
"Picanto",
"Pride",
"Rio",
"Saipa",
"Seltos",
"Sephia",
"Shuma",
"Sorento",
"Soul",
"Spectra",
"Sportage",
"Xceed",
],
},
{
"Manufacturer": "Chevrolet",
"Models": [
"Aveo",
"Blazer",
"Caprice",
"Captiva",
"Celebrity",
"Cruze",
"Equinox",
"Frontera",
"Groove",
"Lanos",
"Malibu",
"N-Series",
"N200",
"N300",
"Optra",
"Pickup",
"Silverado",
"Sonic",
"Spark",
"Spark Lite",
"Sprint",
"Suburban",
"T-Series",
"Tahoe",
"Trax",
],
},
{
"Manufacturer": "Nissan",
"Models": [
"370Z",
"Armada",
"Bluebird",
"Datsun",
"Juke",
"Kicks",
"Laurel",
"Livina",
"Marsh",
"Maxima",
"Murano",
"Pathfinder",
"Patrol",
"Pick up",
"Qashqai",
"Sentra",
"Stanza",
"Sunny",
"Terrano",
"Tiida",
"Urvan",
"Xtrail",
"Z",
"ZX",
],
},
{
"Manufacturer": "Alfa Romeo",
"Models": [
"146",
"156",
"Giulia",
"Giulietta",
"Stelvio",
],
},
{
"Manufacturer": "Aston Martin",
"Models": [
"DB9 Volante",
"Rapide S",
],
},
{
"Manufacturer": "Audi",
"Models": [
"100",
"A1",
"a3",
"a4",
"a5",
"a6",
"a7",
"a8",
"q2",
"Q3",
"Q5",
"Q7",
"Q8",
"TT",
],
},
{
"Manufacturer": "Renault",
"Models": [
"11",
"12",
"16",
"19",
"21",
"5",
"9",
"Austral",
"Captur",
"Clio",
"Duster",
"Duster Nova",
"Fluence",
"Kadjar",
"Laguna",
"Lodgy",
"Logan",
"MCV",
"Megane",
"Optima",
"Rainbow",
"Sandero",
"Sandero Step Way",
"Scala",
"Scenic",
"Symbol",
],
},
{
"Manufacturer": "Toyota",
"Models": [
"86",
"Auris",
"Avanza",
"Avensis",
"Belta",
"Belta",
"C-HR",
"Camry",
"Carina",
"Coaster",
"Corolla",
"Corolla Cross",
"Corona",
"Cressida",
"Echo",
"Fortuner",
"Hiace",
"Hilux",
"Land Cruiser",
"Microbus",
"Prado",
"Rav 4",
"Rumion",
"Rush",
"Sequoia",
"Starlet",
"Tercel",
"Veloz",
"XA",
"Yaris",
],
},
{
"Manufacturer": "Mitsubishi",
"Models": [
"Attrage",
"Colt",
"Eclipse",
"Eclipse Cross",
"Lancer Crystala",
"Lancer EX Shark",
"Lancer Puma",
"Lancer",
"Galant",
"Grandis",
"L300",
"Mirage",
"Pajero",
"Pickup",
"Xpander",
],
},
{
"Manufacturer": "Fiat",
"Models": [
"1100",
"124",
"125",
"126",
"127",
"128",
"1300",
"131",
"132",
"500",
"500 E",
"500 X",
"500C",
"Albea",
"Argenta",
"Brava",
"Bravo",
"Doblo",
"Dogan",
"Fiorino",
"Florida",
"Linea",
"Marea",
"Nova",
"Palio",
"Panda",
"Petra",
"Polonez",
"Punto",
"Punto evo",
"Qubo",
"Regata",
"Ritmo",
"Shahin",
"Siena",
"Tempra",
"Tipo",
"Uno",
],
},
{
"Manufacturer": "Mercedes",
"Models": [
"180",
"190",
"200",
"220",
"230",
"250",
"280",
"300",
"320",
"350",
"450",
"500",
"560",
"600",
"A 140",
"A 150",
"A 180",
"A 200",
"A 250",
"A 45 AMG",
"A Class",
"AMG GT",
"B 150",
"B 160",
"B 180",
"B 200",
"B Class",
"C 180",
"C 200",
"C 200 AMG",
"C 230",
"C 250",
"C 280",
"C 300",
"C 350",
"C 450",
"C63 AMG",
"C Class",
"CL Class",
"CLA 180",
"CLA 200",
"CLA 220",
"CLA 250",
"CLA AMG",
"CLA Class",
"CLC Class",
"CLK",
"CLS Class",
"E 180",
"E 200",
"E 200 AMG",
"E 220",
"E 230",
"E 240",
"E 250",
"E 280",
"E 300",
"E 320",
"E 350",
"E 430",
"E Class",
"EQB",
"EQC",
"EQS",
"G Class",
"GLA 180",
"GLA",
"GLC 250",
"GLC 300",
"GLC 250",
"GLC 300",
"GLC",
"GLC 200",
"GLC 200 AMG Imported",
"GLE",
"GLK 250",
"GLK 300",
"GLK 350",
"GLK",
"GLS",
"ML",
"S 280",
"S 300",
"S 350",
"S 450",
"S 500",
"S 560",
"S Class",
"SEL 350",
"SEL 500",
"SEL",
"V 250",
"Viano",
],
},
{
"Manufacturer": "Skoda",
"Models": [
"Fabia",
"Fantasia",
"Favorit",
"Felicia",
"Foreman",
"Kamiq",
"Karoq",
"Kodiaq",
"Octavia A4",
"Octavia A5",
"Octavia A7",
"Octavia A8",
"Octavia Combi",
"Octavia",
"Rapid",
"Rapid Spaceback",
"Roomster",
"Scala",
"Superb",
"Yeti",
],
},
{
"Manufacturer": "Peugeot",
"Models": [
"1007",
"2008",
"205",
"206",
"207(8)",
"207 SW",
"208",
"3008",
"301",
"305",
"306",
"307",
"308",
"308 sw",
"404",
"405",
"406",
"407",
"408",
"5008",
"504",
"505",
"508",
"605",
"E-2008",
"Partner",
"RCZ",
],
},
{
"Manufacturer": "Opel",
"Models": [
"Adam",
"Astra",
"Calibra",
"Cascada",
"Corsa",
"Corsa E",
"Crossland",
"Grandland",
"Insignia",
"Meriva",
"Mokka",
"Rekord",
"Sintra",
"Tigra",
"Vectra",
"Zafira Tourer",
],
},
{
"Manufacturer": "Baic",
"Models": [
"A1",
"MZ 40",
"X3",
"X35",
"X5",
],
},
{
"Manufacturer": "BMW",
"Models": [
"116",
"118",
"120",
"135",
"1 Series",
"218 i",
"220",
"2 Series",
"218",
"230",
"316",
"318",
"320",
"323",
"325",
"328",
"330",
"340",
"M3",
"3 Series",
"418",
"420",
"430",
"4 Series",
"440i",
"518",
"520",
"523",
"525",
"528",
"530",
"535",
"M5",
"5 Series",
"730",
"735",
"740",
"750",
"7 Series",
"I3",
"I8",
"IX3",
"M850",
"X1",
"X2",
"X3",
"X3 M",
"X4",
"X5",
"X5 M",
"X6",
"X6 M",
"X7",
"Z4",
"Z Series",
],
},
{
"Manufacturer": "MG",
"Models": [
"3",
"350",
"360",
"5",
"6",
"7",
"750",
"GT",
"HS",
"One",
"Rx5",
"RX5 Plus",
"ZR",
"ZS",
"ZS EV",
],
},
{
"Manufacturer": "Changan",
"Models": [
"Alsvin",
"Benni",
"CS 15",
"CS 35",
"CS 35 Plus",
"CS 55",
"CS55 Plus",
"Eado",
"Eado plus",
"V3",
"V7",
],
},
{
"Manufacturer": "Jetour",
"Models": [
"Dashing",
"X70",
"X70 Plus",
"X70S",
"X95",
],
},
{"Manufacturer": "Seat", "Models": ["131", "133", "Altea", "Altea XL", "Arona", "Ateca", "Cordoba", "Ibiza", "Leon", "Tarraco", "Toledo", "Yrv"]},
{"Manufacturer": "Citroën", "Models": ["Ax", "Berlingo", "C Elysee", "C3", "C3 Aircross", "C3 Picasso", "C4", "C4 Grand Picasso", "C4 Picasso", "C4X", "C5", "C5 Aircross", "Grand C4 Spacetourer", "Jumpy", "Xsara", "ZX"]},
{"Manufacturer": "Bestune", "Models": ["B70", "T33", "T55", "T77 Pro"]},
{"Manufacturer": "Suzuki", "Models": ["Alto", "APV", "Baleno", "Carry", "Celerio", "Ciaz", "Ertiga", "Fronx", "Grand vitara", "Jimny", "Maruti", "Pickup", "S Presso", "Swift", "Swift Dzire", "Sx4", "Van", "Vitara", "XL 7"]},
{"Manufacturer": "Kaiyi", "Models": ["X3", "X3 Pro"]},
{"Manufacturer": "Volvo", "Models": ["144", "240", "340", "460", "740", "760", "940", "S60", "S80", "S90", "V60", "XC 40", "XC60", "XC90"]},
{"Manufacturer": "Ssang Yong", "Models": ["Musso", "Tivoli", "Tivoli XLV"]},
{"Manufacturer": "Chery", "Models": ["A11", "A15", "A3", "Arrizo 3", "Arrizo 5", "Arrizo 5 pro", "Envy", "Tiggo", "Tiggo 2", "Tiggo 2 Pro", "Tiggo 3", "Tiggo 4", "Tiggo 4 Pro", "Tiggo 7", "Tiggo 7 pro", "Tiggo 7 pro max", "Tiggo 8", "Tiggo 8 Pro", "X5"]},
{"Manufacturer": "Cupra", "Models": ["Formentor", "Leon"]},
{"Manufacturer": "Volkswagen", "Models": ["Beetle", "Bora", "Caddy", "CC", "Cross", "Eos", "Fox", "Gol", "Golf 1", "Golf 2", "Golf 3", "Golf 4", "Golf 5", "Golf 6", "Golf 7", "Golf 8", "Golf", "ID 4", "ID 6", "Jetta", "Parati", "Passat", "Pointer", "Polo", "Scirocco", "Suran", "T-Roc", "Teramont", "Tiguan", "Touareg", "Transporter", "Turan"]},
{"Manufacturer": "Dongfeng", "Models": ["A30", "Aeolus A30", "Venucia Star"]},
{"Manufacturer": "Lada", "Models": ["1200", "124", "1300", "1500", "2017", "2104", "2105", "2106", "2107", "2110", "2111", "Granta", "Kalina", "Largus", "Niva", "Priora", "Samara"]},
{"Manufacturer": "Jac", "Models": ["A 10", "B15", "Eagle", "J2", "J3", "J7", "JS3", "JS4", "S2", "S3", "S4", "S5", "S7", "Tons 4", "Tons 5.5", "Tons2 / 2.5"]},
{"Manufacturer": "Byd", "Models": ["F0", "F3", "F3R", "Flyer", "L3", "Qin Pro", "S5", "Yuan plus"]},
{"Manufacturer": "Porsche", "Models": ["718", "911", "Boxster", "Boxster S", "Cayenne", "Cayenne S", "Macan", "Panamera", "Panamera S", "Taycan"]},
{"Manufacturer": "Proton", "Models": ["Exora", "Gen 2", "Persona", "Preve", "Saga", "Waja", "Wira"]},
{"Manufacturer": "Jaguar", "Models": ["F-Pace", "F-Type", "S-Type", "X-Type", "XE", "XF", "XJ"]},
{"Manufacturer": "DFSK", "Models": ["330S", "C31", "EAGLE 580", "Eagle pro", "Glory", "Glory 330", "Glory Van", "K01", "K01s"]},
{"Manufacturer": "Mini", "Models": ["Clubman", "Convertible", "Cooper", "Cooper Hatch", "Country man", "Countryman S", "Coupe", "Mini Cooper S"]},
{"Manufacturer": "Honda", "Models": ["Accord", "City", "Civic", "CRV", "CRX", "ENS1", "HRV", "Integra", "Legend", "MRV", "Odyssey", "Vigor"]},
{"Manufacturer": "Ford", "Models": ["B-Max", "Bronco", "EcoSport", "Escape", "Escort", "Explorer", "F-150", "F350", "Fiesta", "Focus", "Fusion", "Grand C-Max", "Ka", "Kuga", "Mondeo", "Mustang", "Ranger", "Taunus", "Taurus", "Territory", "Thunderbird", "Transit"]},
{"Manufacturer": "Ds", "Models": ["DS3", "Ds4", "DS5", "DS7"]},
{"Manufacturer": "Forthing", "Models": ["T5 evo"]},
{"Manufacturer": "Land Rover", "Models": ["Defender", "Discovery", "Discovery sport", "Freelander", "LR2", "lr3", "Range Rover", "Range Rover Evoque", "Range Rover Sport", "Range Rover Vogue", "Velar"]},
{"Manufacturer": "Mazda", "Models": ["121", "2", "232", "3", "323", "626", "929", "Cx 3", "Familia", "Pickup"]},
{"Manufacturer": "Subaru", "Models": ["Impreza", "Legacy", "Outback", "Vivio", "XV"]},
{"Manufacturer": "Geely", "Models": ["Ck", "Ck2", "Cool Ray", "EC7", "Emgrand", "Emgrand 5", "Emgrand 7", "Emgrand X7", "Englon", "EX7", "Fruits", "GS", "GX3 Pro", "Imperial", "Maple", "Mk", "Okavango", "Panda", "Pandino", "Sparky", "X Pandino", "X7"]},
{"Manufacturer": "Jaguar", "Models": ["F-Pace", "F-Type", "S-Type", "X-Type", "XE", "XF", "XJ"]},
{"Manufacturer": "Maserati", "Models": ["Quattroporte"]},
{"Manufacturer": "Soueast", "Models": ["Crystala", "DX3", "DX5", "DX7", "DX8S Coupe", "V3", "V5"]},
{"Manufacturer": "Haval", "Models": ["Dargo", "H2", "H6", "H6 GT", "Jolion"]},
{"Manufacturer": "GAC", "Models": ["Emkoo", "GA3"]}
];
// List<String> car_modals = [
// "Abarth",
// "AC",
// "Acura",
// "AIXAM",
// "Alfa Romeo",
// "Alpine",
// "Arash",
// "Ariel",
// "Ascari",
// "Aston Martin",
// "Audi",
// "AvtoVAZ",
// "BAIC",
// "Bentley",
// "BMW",
// "Borgward",
// "Brilliance",
// "Bristol",
// "Bufori",
// "Bugatti",
// "Buick",
// "Byton",
// "Cadillac",
// "Caterham",
// "Changan",
// "Chery",
// "Chevrolet",
// "Chrysler",
// "Citroen",
// "Dacia",
// "Daewoo",
// "DAF",
// "Daihatsu",
// "Datsun",
// "Dodge",
// "DS",
// "Ferrari",
// "Fiat",
// "Fisker",
// "Ford",
// "Foton",
// "GAZ",
// "Geely",
// "Genesis",
// "Ginetta",
// "GMC",
// "Great Wall",
// "Haima",
// "Hino",
// "Holden",
// "Honda",
// "Hyundai",
// "Isuzu",
// "JAC",
// "Jaguar",
// "Jeep",
// "JMC",
// "Kia",
// "Koenigsegg",
// "Lamborghini",
// "Lancia",
// "Land Rover",
// "Landwind",
// "Lexus",
// "Lifan",
// "Lincoln",
// "Lotus",
// "Luxgen",
// "Magna Steyr",
// "Mahindra",
// "Maserati",
// "Maxus",
// "Maybach",
// "Mazda",
// "McLaren",
// "Mercedes-Benz",
// "MG",
// "Mini",
// "Mitsubishi",
// "Mitsuoka",
// "Morgan",
// "Morris",
// "NIO",
// "Nissan",
// "Noble",
// "Opel",
// "Pagani",
// "Perodua",
// "Peugeot",
// "Polestar",
// "Pontiac",
// "Porsche",
// "Proton",
// "Ram",
// "Reliant",
// "Renault",
// "Rivian",
// "Rolls-Royce",
// "RUF",
// "Saab",
// "Saleen",
// "Saturn",
// "Scion",
// "SEAT",
// "Senova",
// "Smart",
// "Spyker",
// "Ssangyong",
// "Subaru",
// "Suzuki",
// "Tata",
// "Tatra",
// "Tesla",
// "Toyota",
// "Trumpchi",
// "TVR",
// "Vauxhall",
// "Volkswagen",
// "Volvo",
// "W Motors",
// "Zenos",
// "Zenvo"
// ];
